config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  # Путь для админки
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Пути для формы регистрации, входа и т.д.
  devise_for :users

  # В профиле юзера показываем его игры, на главной — список лучших игроков
  resources :users, only: [:index, :show]

  resources :games, only: [:create, :show] do
    # Доп. методы ресурса:
    put 'help', on: :member # помощь зала
    put 'answer', on: :member # ответ на текущий вопрос
    put 'take_money', on: :member #  игрок берет деньги
  end

  # Ресурс в единственном числе — ВопросЫ
  # для загрузки админом сразу пачки вопросОВ
  resource :questions, only: [:new, :create]
end

app/models/game.rb
#  (c) goodprogrammer.ru
#
# Модельи игры — создается когда пользователь начинает новую игру. Хранит и
# обновляет состояние игры и отвечает за игровой процесс.
class Game < ActiveRecord::Base
  PRIZES = [100, 200, 300, 500, 1_000, 2_000, 4_000, 8_000, 16_000,
            32_000, 64_000, 125_000, 250_000, 500_000, 1_000_000].freeze
  FIREPROOF_LEVELS = [4, 9, 14].freeze
  TIME_LIMIT = 35.minutes

  belongs_to :user
  has_many :game_questions, dependent: :destroy

  scope :in_progress, -> { where(finished_at: nil) }

  validates :user, presence: true
  validates :current_level, numericality: {only_integer: true}, allow_nil: false
  validates :prize, presence: true, numericality: {
    greater_than_or_equal_to: 0, less_than_or_equal_to: PRIZES.last
  }

  def self.create_game_for_user!(user)
    transaction do
      game = create!(user: user)

      Question::QUESTION_LEVELS.each do |level|
        question = Question.where(level: level).order('RANDOM()').first

        answers = [1, 2, 3, 4].shuffle

        game.game_questions.create!(
          question: question,
          a: answers.pop, b: answers.pop,
          c: answers.pop, d: answers.pop
        )
      end

      game
    end
  end

  def current_game_question
    game_questions.detect { |q| q.question.level == current_level }
  end

  def previous_level
    current_level - 1
  end

  def finished?
    finished_at.present?
  end

  def time_out!
    if (Time.now - created_at) > TIME_LIMIT
      finish_game!(fire_proof_prize(previous_level), true)
      true
    end
  end

  def answer_current_question!(letter)
    return false if time_out! || finished?

    # С помощью метода answer_correct? у текущего игрового вопроса проверяем,
    # правильно ли ответили на текущий вопрос.
    if current_game_question.answer_correct?(letter)

      # Если это был последний вопрос, заканчиваем игру методом finish_game!
      if current_level == Question::QUESTION_LEVELS.max
        self.current_level += 1
        finish_game!(PRIZES[Question::QUESTION_LEVELS.max], false)
      else
        # Если нет, сохраняем игру и идем дальше
        self.current_level += 1
        save!
      end

      true
    else
      # Если ответили неправильно, заканчиваем игру методом finish_game! и
      # возвращаем false.
      finish_game!(fire_proof_prize(previous_level), true)
      false
    end
  end

  def take_money!
    return if time_out! || finished?

    finish_game!(previous_level > -1 ? PRIZES[previous_level] : 0, false)
  end

  # Создает варианты подсказок для текущего игрового вопроса.
  # Возвращает true, если подсказка применилась успешно,
  # nil если подсказка уже заюзана.
  def use_help(help_type)
    field_name = "#{help_type}_used".to_sym
    method_name = "add_#{help_type}"

    unless read_attribute(field_name)
      toggle!(field_name)
      current_game_question.send(method_name)
      return true
    end
  end

  def status
    return :in_progress unless finished?

    if is_failed
      (finished_at - created_at) > TIME_LIMIT ? :timeout : :fail
    elsif current_level > Question::QUESTION_LEVELS.max
      :won
    else
      :money
    end
  end

  private

  def finish_game!(amount = 0, failed = true)
    transaction do
      self.prize = amount
      self.finished_at = Time.now
      self.is_failed = failed
      user.balance += amount
      save!
      user.save!
    end
  end

  def fire_proof_prize(answered_level)
    level = FIREPROOF_LEVELS.select { |x| x <= answered_level }.last
    level.present? ? PRIZES[level] : 0
  end
end

app/controllers/games_controller.rb
# (c) goodprogrammer.ru
#
# Основной игровой контроллер
# Создает новую игру, обновляет статус игры по ответам юзера, выдает подсказки
class GamesController < ApplicationController
  before_action :authenticate_user!

  # Проверка нет ли у залогиненного юзера начатой игры
  before_action :goto_game_in_progress!, only: [:create]

  # Загружаем игру из базы для текущего юзера
  before_action :set_game, except: [:create]

  # Проверка — если игра завершена, отправляем юзера на его профиль, где он
  # может увидеть статистику сыгранных игр.
  before_action :redirect_from_finished_game!, except: [:create]

  def show
    @game_question = @game.current_game_question
  end

  # Действие create создает новую игру и отправляет на действие show (основной
  # игровой экран) в случае успеха.
  def create
    begin
      # Создаем игру для залогиненного юзера
      @game = Game.create_game_for_user!(current_user)

      # Отправляемся на страницу игры
      redirect_to game_path(@game), notice: I18n.t(
        'controllers.games.game_created',
        created_at: @game.created_at
      )
    rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotSaved => ex
      # Если ошибка создания игры
      Rails.logger.error("Error creating game for user #{current_user.id}, " \
                         "msg = #{ex}. #{ex.backtrace}")

      # Отправляемся назад с алертом
      redirect_to :back, alert: I18n.t('controllers.games.game_not_created')
    end
  end

  # Действие answer принимает ответ на вопрос, единственный обязательный
  # параметр — params[:letter] — буква, которую выбрал игрок.
  def answer
    # Выясняем у игры, правильно ли оветили
    @answer_is_correct = @game.answer_current_question!(params[:letter])
    @game_question = @game.current_game_question

    unless @answer_is_correct
      # Если ответили неправильно, отправляем юзера на профиль с сообщением
      flash[:alert] = I18n.t(
        'controllers.games.bad_answer',
        answer: @game_question.correct_answer,
        prize: view_context.number_to_currency(@game.prize)
      )
    end

    # Выбираем поведение в зависимости от формата запроса
    respond_to do |format|
      # Если это html-запрос, по-старинке редиректим пользователя в зависимости
      # от ситуации
      format.html do
        if @answer_is_correct && !@game.finished?
          redirect_to game_path(@game)
        else
          redirect_to user_path(current_user)
        end
      end

      # Если это js-запрос, то ничего не делаем и контролл попытается отрисовать
      # шаблон
      #
      # <controller>/<action>.<format>.erb
      #
      # В нашем случае будет games/answer.js.erb
      format.js {}
    end

  end

  # Действие take_money вызывается из шаблона, когда пользователь берет кнопку
  # «Взять деньги». Параметров нет, т.к. вся необходимая информация есть в базе.
  def take_money
    # Заканчиваем игру
    @game.take_money!

    # Отправялем пользователя на профиль с сообщение о выигрыше
    redirect_to user_path(current_user), flash: {
      warning: I18n.t(
        'controllers.games.game_finished',
        prize: view_context.number_to_currency(@game.prize)
      )
    }
  end

  # запрашиваем помощь в текущем вопросе
  # params[:help_type]
  def help
    # используем помощь в игре и по результату задаем сообщение юзеру
    msg = if @game.use_help(params[:help_type].to_sym)
            {flash: {info: I18n.t('controllers.games.help_used')}}
          else
            {alert: I18n.t('controllers.games.help_not_used')}
          end

    redirect_to game_path(@game), msg
  end


  private

  def redirect_from_finished_game!
    if @game.finished?
      redirect_to user_path(current_user), alert: I18n.t(
        'controllers.games.game_closed',
        game_id: @game.id
      )
    end
  end

  def goto_game_in_progress!
    # Вот нам и пригодился наш scope in_progress из модели Game
    game_in_progress = current_user.games.in_progress.first

    unless game_in_progress.blank?
      redirect_to game_path(game_in_progress), alert: I18n.t(
        'controllers.games.game_not_finished'
      )
    end
  end

  def set_game
    @game = current_user.games.find_by(id: params[:id])

    if @game.blank?
      # Если у current_user нет игры - посылаем
      redirect_to root_path, alert: I18n.t(
        'controllers.games.not_your_game'
      )
    end
  end
end

app/helpers/games_helper.rb
# Этот файл будет автоматически загружен при отрисовке шаблона
# Мы будем складывать в него все вспомогательные методы, которые захотим использовать в шаблонах,
# связаныхх с отображением игр
module GamesHelper
  # Этот метод будет рисовать удобный ярлычок для показа статуса игры
  # Используем стандартные bootstrap-овский класс `label`
  def game_label(game)
    if game.status == :in_progress && current_user == game.user
      link_to content_tag(:span, t("game_statuses.#{game.status}"), class: 'label'), game_path(game)
    else
      content_tag :span, t("game_statuses.#{game.status}"), class: 'label label-danger'
    end
  end
end

app/views/games/_game_question.html.erb
<%# Шаблон, которые будет выводить вопрос и варианты ответа на странице игры %>

<% game = game_question.game %>
<% help = game_question.help_hash %>

<div class="alert alert-info text-center">
  <h2><%= game_question.text %></h2>
</div>

<div class="row">
  <% game_question.variants.each do |letter, variant| %>
    <%# Если была использована подсказка 50/50, нам нужно проверить, есть ли вариант среди оставшихся %>
    <% if !help.key?(:fifty_fifty) || help[:fifty_fifty].include?(letter) %>
      <div class="col-md-6 buffer-top">
        <%= link_to content_tag(:span, letter.upcase, class: 'variant') + ": #{variant}",
                    answer_game_path(game, letter: letter),
                    method: :put,
                    remote: true,
                    class: 'btn btn-block btn-default btn-variant'
        %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/games/_help.html.erb
<%# Фрагмент для вывода кнопок подсказок, а также информации из этих подсказок %>

<div class="game-help-info">
  <%# Если в хэше help есть ключь friend_call или audience_help, нам есть что показать пользователю %>
  <% if help.key?(:friend_call) || help.key?(:audience_help) %>
    <div class="row buffer-top-lg">
      <div class="col-xs-12">
        <%# Выводим информацию о подсказке "Звонок другу" %>
        <% if help.key?(:friend_call) %>
          <div class="alert alert-info text-center">
            <%= help[:friend_call] %>
          </div>
        <% end %>

        <% if help.key?(:audience_help) %>
          <p>Зрители считают: </p>
          <%# Выводим распределение голосов зрителей %>
          <% help[:audience_help].sort.map do |key, value| %>
            <div class="progress">
              <div class="progress-bar progress-bar-danger" style="width: <%= value %>%;">
                <%= key.upcase %>: <%= value %>%
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<%# Выводим подсказки, которые можно использовать во время игры %>
<div class="game-help row buffer-top">
  <div class="col-sm-4">
    <%# Для каждой подсказки с помощью объекта game проверяем, не была ли подсказка использована ранее %>
    <% unless game.fifty_fifty_used? %>
      <%= link_to '50/50', help_game_path(game, help_type: :fifty_fifty), method: :put, class: 'btn btn-default btn-block btn-help' %>
    <% end %>
  </div>
  <div class="col-sm-4">
    <% unless game.friend_call_used? %>
      <%= link_to fa_icon('phone'), help_game_path(game, help_type: :friend_call), method: :put, class: 'btn btn-default btn-block btn-help' %>
    <% end %>
  </div>
  <div class="col-sm-4">
    <% unless game.audience_help_used? %>
      <%= link_to fa_icon('users'), help_game_path(game, help_type: :audience_help), method: :put, class: 'btn btn-default btn-block btn-help' %>
    <% end %>
  </div>
</div>

app/views/games/answer.js.erb
<%# Этот js-код будет выполнен прямо на странице игры, используя информацию от сервера %>

<% if @answer_is_correct && !@game.finished? %>
  <%# Если игра ещё не закончена (был дан правильный ответ на не последний вопрос), %>
  <%# то нам надо немного обновить экран: %>
  <%# вывести новый вопрос, поменять текущий приз и скрыть старые подсказки %>

  $('.game-question').html("<%= escape_javascript (
      render partial: 'game_question', object: @game_question
    ) %>");

  current_prize = $('.game-prizes').find('.active').toggleClass('active');
  current_prize.prev().toggleClass('active');

  $('.game-help-info').hide();
<% else %>
  <%# Если игра закончилась, тупо редиректим на профиль с помощью js %>

  window.location.href = '<%= user_path(current_user) %>';
<% end %>

app/views/games/show.html.erb
<div class="row">
  <div class="col-sm-9 col-sm-push-3">
    <div class="text-center">
      <%= image_tag asset_path('logo.png'), class: 'game-logo buffer-bottom' %>
    </div>

    <div class="game-question">
      <%# Выводим шаблон с текстом вопроса и вариантами ответа %>
      <%= render partial: 'game_question', object: @game_question %>
    </div>

    <div class="buffer-top-lg">
      <%# Выводим шаблон с кнопками для подсказок и информацией о подсказках %>
      <%= render partial: 'help', object: @game_question.help_hash, locals: {game: @game} %>
    </div>
  </div>

  <div class="col-sm-3 col-sm-pull-9">
    <ul class="list-group list-group-prizes game-prizes">
      <% Game::PRIZES.reverse.each_with_index do |prize, index| %>
        <li class="list-group-item text-center <%= 'active' if (14 - index == @game.current_level) %>">
          <%= fa_icon('diamond') if Game::FIREPROOF_LEVELS.include?(14-index) %>
          <%= prize %>
        </li>
      <% end %>
    </ul>

    <%= link_to 'Забрать выигрыш', take_money_game_path(@game), method: :put, class: 'btn btn-info btn-block' %>
  </div>
</div>